@ArticleAggregator.WebApi_HostAddress = http://localhost:5183

GET {{ArticleAggregator.WebApi_HostAddress}}/todos/
Accept: application/json

###

GET {{ArticleAggregator.WebApi_HostAddress}}/todos/1
Accept: application/json

###
